# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(800, 600)
        MainWidget.setMinimumSize(QtCore.QSize(800, 600))
        MainWidget.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileList = QtWidgets.QListView(MainWidget)
        self.fileList.setObjectName("fileList")
        self.horizontalLayout.addWidget(self.fileList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addBtn = QtWidgets.QPushButton(MainWidget)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout.addWidget(self.addBtn)
        self.deleteBtn = QtWidgets.QPushButton(MainWidget)
        self.deleteBtn.setEnabled(False)
        self.deleteBtn.setObjectName("deleteBtn")
        self.verticalLayout.addWidget(self.deleteBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.clearBtn = QtWidgets.QPushButton(MainWidget)
        self.clearBtn.setEnabled(False)
        self.clearBtn.setObjectName("clearBtn")
        self.verticalLayout.addWidget(self.clearBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resizeCheckBox = QtWidgets.QCheckBox(MainWidget)
        self.resizeCheckBox.setObjectName("resizeCheckBox")
        self.gridLayout_2.addWidget(self.resizeCheckBox, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(MainWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widthEdit = QtWidgets.QLineEdit(MainWidget)
        self.widthEdit.setEnabled(False)
        self.widthEdit.setObjectName("widthEdit")
        self.gridLayout.addWidget(self.widthEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(MainWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.heightEdit = QtWidgets.QLineEdit(MainWidget)
        self.heightEdit.setEnabled(False)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.startBtn = QtWidgets.QPushButton(MainWidget)
        self.startBtn.setEnabled(False)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_2.addWidget(self.startBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(MainWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(MainWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.outputPathEdit = QtWidgets.QLineEdit(MainWidget)
        self.outputPathEdit.setObjectName("outputPathEdit")
        self.horizontalLayout_3.addWidget(self.outputPathEdit)
        self.browserBtn = QtWidgets.QPushButton(MainWidget)
        self.browserBtn.setObjectName("browserBtn")
        self.horizontalLayout_3.addWidget(self.browserBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_2)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "图片转字符"))
        self.addBtn.setText(_translate("MainWidget", "添加"))
        self.deleteBtn.setText(_translate("MainWidget", "删除"))
        self.clearBtn.setText(_translate("MainWidget", "清空"))
        self.resizeCheckBox.setText(_translate("MainWidget", "自定义大小"))
        self.label.setText(_translate("MainWidget", "宽度（字符）"))
        self.widthEdit.setText(_translate("MainWidget", "240"))
        self.label_2.setText(_translate("MainWidget", "高度（字符）"))
        self.heightEdit.setText(_translate("MainWidget", "80"))
        self.startBtn.setText(_translate("MainWidget", "开始"))
        self.label_3.setText(_translate("MainWidget", "保存在："))
        self.browserBtn.setText(_translate("MainWidget", "浏览"))
